feat!: change default plugin dir
devstream-io/devstream pull request #1004
Opened 2022-08-18 03:43 UTC by iyear

Signed-off-by: iyear <ljyngup@gmail.com>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description
A simpler solution to the plugin absolute path problem that does not affect documentation.

The only impact is that the developer needs to specify `-d .devstream` when debugging the plugin.

## Related Issues
close #997 

## New Behavior (screenshots if needed)
The plugin version shown is for demonstration purposes only, not the actual situation.

<img width="813" alt="linux" src="https://user-images.githubusercontent.com/61452000/185288157-7d7fe902-df97-4e67-b5e0-c2c3ee21c17b.PNG">
<img width="794" alt="windows" src="https://user-images.githubusercontent.com/61452000/185288174-62b43e50-4962-45c9-b5dc-d48ed4a15a85.PNG">
<img width="897" alt="dev-plugin" src="https://user-images.githubusercontent.com/61452000/185288182-a9fbf45c-02a8-4be2-83ae-2debac325aba.PNG">

2022-08-18 08:02 UTC, iyear commented
@devstream-io/reviewer 
## New Behavior
only set flag:

<img width="831" alt="set-flag" src="https://user-images.githubusercontent.com/61452000/185342474-1d609f52-c05d-4021-88e8-edaa38fc2652.PNG">

only set config:

<img width="828" alt="set-config" src="https://user-images.githubusercontent.com/61452000/185342557-694e259d-6ba2-45c6-8858-47012670b7fd.PNG">

default value:

<img width="816" alt="set-default" src="https://user-images.githubusercontent.com/61452000/185342614-c9a97c33-bf0e-4e1a-ac50-c4843ae17d4a.PNG">

set both flag and config(flag has higher priority):

<img width="820" alt="set-both-flag-config" src="https://user-images.githubusercontent.com/61452000/185342684-eb58c37c-85c6-4356-a598-8d7df19e4fe0.PNG">

2022-08-18 08:25 UTC, daniel-hutao requested changes
Good job!

Please test this pr fully, as it is a very basic feature, to avoid introducing more serious bugs.

2022-08-18 08:25 UTC, daniel-hutao commented on cmd/devstream/init.go
> +	"github.com/devstream-io/devstream/pkg/util/file"
goimports

2022-08-18 08:25 UTC, daniel-hutao commented on docs/core-concepts/config.md
> +pluginDir: /usr/local/.devstream/plugins # optional
I think `/usr/local/devstream/plugins` is better here.

2022-08-18 08:25 UTC, daniel-hutao commented on internal/pkg/pluginengine/cmd_apply.go
> +	"github.com/devstream-io/devstream/pkg/util/file"
goimports

2022-08-18 08:25 UTC, daniel-hutao commented on internal/pkg/pluginengine/cmd_delete.go
> +
goimports

2022-08-18 08:25 UTC, daniel-hutao commented on internal/pkg/pluginengine/cmd_destroy.go
> +
goimports

2022-08-18 08:25 UTC, daniel-hutao commented on internal/pkg/show/status/status.go
> +
goimports

2022-08-18 08:51 UTC, daniel-hutao approved these changes

2022-08-19 06:43 UTC, IronCore864 approved these changes

2022-08-19 06:43 UTC, merged