feat: create namespace auto check if exist
devstream-io/devstream pull request #1016
Opened 2022-08-19 04:44 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description
- plugin installed by helm support default namespace, with name pluginname
- update doc for override default value
- namepsace support upsert

## Related Issues
close #1014

2022-08-19 06:40 UTC, daniel-hutao requested changes
I think we can remove the `create_namespace` param and create ns when the ns is not exists.

2022-08-19 06:46 UTC, IronCore864 approved these changes

2022-08-19 06:46 UTC, IronCore864 commented
> I think we can remove the `create_namespace` param and create ns when the ns is not exists.

I agree with Daniel here; the param `create_namespace` seems redundant now.

2022-08-22 01:24 UTC, iyear approved these changes
LGTM

2022-08-22 05:48 UTC, daniel-hutao approved these changes

2022-08-22 05:50 UTC, merged