feat: pkg/util/k8s add ut
devstream-io/devstream pull request #1031
Opened 2022-08-25 15:56 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
add more unit test for pkg/util/k8s package

## Related Issues
close #1015

## New Behavior (screenshots if needed)
![image](https://user-images.githubusercontent.com/13215800/186712562-f7f40425-a59f-46ac-954a-4e4b4f43d4e3.png)

2022-08-27 00:32 UTC, iyear approved these changes
LGTM 👏

2022-08-27 07:30 UTC, aFlyBird0 commented on pkg/util/k8s/configmap_test.go
> +			})
You didn't call `ApplyConfig` so how did you test this function?

2022-08-27 07:32 UTC, aFlyBird0 commented on pkg/util/k8s/configmap_test.go
> +				currectConfigMap, err := client.clientset.CoreV1().ConfigMaps(
typo

2022-08-27 07:43 UTC, aFlyBird0 requested changes

2022-08-27 07:43 UTC, aFlyBird0 commented on pkg/util/k8s/configmap_test.go
> +		})
Maybe this way is better. (The code is copied from `Context("ApplyConfigMap method", func() {...`, I just edit the prompt and var name)
```go
BeforeEach(func() {
			testConfigMap = []runtime.Object{&v1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name:      configmapName,
					Namespace: namespace,
					Labels:    labels,
				},
				Data: data,
			}}
			client.clientset = fake.NewSimpleClientset(testConfigMap...)
		})
		It("should get correct configmap", func() {
			currentConfigMap, err := client.clientset.CoreV1().ConfigMaps(
				namespace).Get(context.Background(), configmapName, metav1.GetOptions{})
			Expect(err).Error().ShouldNot(HaveOccurred())
			Expect(currentConfigMap.Data).Should(Equal(data))
			Expect(currentConfigMap.ObjectMeta.Labels).Should(Equal(labels))
		})
```

2022-08-27 07:43 UTC, aFlyBird0 commented on pkg/util/k8s/configmap_test.go
> +		})
Maybe you could add the `Context` when "configmap is exist". (The code is copied from `Context("ApplyConfigMap method", func() {...`, I just edit the prompt and var name)
```go
BeforeEach(func() {
			testConfigMap = []runtime.Object{&v1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name:      configmapName,
					Namespace: namespace,
					Labels:    labels,
				},
				Data: data,
			}}
			client.clientset = fake.NewSimpleClientset(testConfigMap...)
		})
		It("should get correct configmap", func() {
			currentConfigMap, err := client.clientset.CoreV1().ConfigMaps(
				namespace).Get(context.Background(), configmapName, metav1.GetOptions{})
			Expect(err).Error().ShouldNot(HaveOccurred())
			Expect(currentConfigMap.Data).Should(Equal(data))
			Expect(currentConfigMap.ObjectMeta.Labels).Should(Equal(labels))
		})
```

2022-08-27 07:45 UTC, aFlyBird0 commented
Thanks for creating detailed uts for `k8s` pkg. 👏

2022-08-30 01:52 UTC, daniel-hutao approved these changes

2022-08-30 01:53 UTC, merged