feat: Jenkins repo support private repo
devstream-io/devstream pull request #1105
Opened 2022-09-19 09:40 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description
- `Jenkins` support clone private repo
- delete `scm.projectRepo` and `scm.projectBranch` field
- add `scm.cloneURL` for clone config, `scm.apiURL` for api request, `scm.branch` for repo branch config
- add `GITLAB_SSHKEY` environment variable for private repo

## Related Issues
#993 

## New Behavior (screenshots if needed)
- create `Jenkins` credential for private key
![image](https://user-images.githubusercontent.com/13215800/190990493-466996ee-0bf1-457e-8949-ef73cfd13706.png)
- create job with this credential
![image](https://user-images.githubusercontent.com/13215800/190990619-3bc17dc5-d253-47b4-92d8-c478520f25e3.png)

2022-09-19 13:31 UTC, daniel-hutao commented on docs/plugins/jenkins-pipeline.zh.md
> +export GITLAB_SSHKEY=YOUR_REPO_PRIVATE_KEY
What does YOUR_REPO_PRIVATE_KEY mean?

2022-09-20 03:20 UTC, daniel-hutao commented on docs/plugins/jenkins-pipeline.zh.md
> +export GITLAB_SSHKEY=YOUR_REPO_PRIVATE_KEY
> This is your ssh private key for clone repo

Oh, yeah I've got it. I thought it's token yesterday.

2022-09-20 03:24 UTC, daniel-hutao requested changes

2022-09-20 03:24 UTC, daniel-hutao commented on docs/plugins/jenkins-pipeline.zh.md
> +      cloneURL: git@YOUR_REPO_CLONE_ADDRESS/root/spring-demo
Please help to update `docs/best-practices/gitlab-jenkins-harbor.zh.md` as well.

2022-09-20 03:30 UTC, aFlyBird0 commented on internal/pkg/plugininstaller/jenkins/option.go
> +		return nil
why should here `return nil`?

2022-09-20 06:59 UTC, daniel-hutao commented
Remember close #1102 after this pr merged.

2022-09-20 08:04 UTC, daniel-hutao approved these changes

2022-09-21 01:57 UTC, aFlyBird0 approved these changes

2022-09-21 03:35 UTC, merged