feat: add devlake-config update method
devstream-io/devstream pull request #1176
Opened 2022-10-16 04:04 UTC by warren830

Signed-off-by: Yingchu Chen <yingchu.chen@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [X] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [X] My code has the necessary comments and documentation (if needed).
- [X] I have added relevant tests

## Description
1. modified the definition of Connection and comment RenderAuthConfig
2. add devlake-config UpdateConfig

2022-10-17 06:17 UTC, daniel-hutao requested changes
@warren830 Thanks for your contributions! I've left some comments here.

2022-10-17 06:17 UTC, daniel-hutao commented on internal/pkg/plugin/devlakeconfig/devlakeconfig.go
> +func updateConnection(host string, pluginName string, c Connection) error {
How about to add some blank lines or comments in this function? I think it will be more readable.

2022-10-17 06:17 UTC, daniel-hutao commented on internal/pkg/plugin/devlakeconfig/devlakeconfig.go
> +func deleteConnection(host string, pluginName string, c Connection) error {
How about to add some blank lines or comments in this function? I think it will be more readable.

2022-10-17 06:17 UTC, daniel-hutao commented on internal/pkg/plugin/devlakeconfig/devlakeconfig.go
> +	cfg, err := configmanager.NewManager("config-devlake-config.yaml").LoadConfig()
You can get the `Config` from options(function param). ConfigManager is used in `core` only for the "config file name" is only known by core. It's not the "config-devlake-config.yaml".

2022-10-17 06:17 UTC, daniel-hutao commented on internal/pkg/plugin/devlakeconfig/devlakeconfig.go
> +	smgr, _ := statemanager.NewManager(*cfg.State)
Missing the error handle process here.

2022-10-17 06:17 UTC, daniel-hutao commented on internal/pkg/plugin/devlakeconfig/devlakeconfig.go
> +	stateLakeConfig := smgr.GetState("devlake-config_default")
"key" isn't the "devlake-config_default" here. Users can customise "instanceID" by themselves. Maybe the plugins shouldn't try to get the "State" and compare it to "Config". One way to implement "Update" is that the plugins get the "Resource state" and compare it to "Config" and then decide how to "Update".

2022-10-17 09:51 UTC, daniel-hutao commented on internal/pkg/plugin/devlakeconfig/devlakeconfig.go
> +//func RenderAuthConfig(options plugininstaller.RawOptions) (plugininstaller.RawOptions, error) {
> We can delete this function if it's not needed for now.

@IronCore864 It's needed. I'll keep communicating with @warren830 for this.

2022-10-17 11:21 UTC, daniel-hutao commented
@warren830 Please take a look at this pr: #1181

I refactored the State/Resource in that pr.

2022-10-18 11:46 UTC, warren830 commented on internal/pkg/plugin/devlakeconfig/devlakeconfig.go
> +	fmt.Println(string(configs))
Haha, I will delete all these stuff before I submit pr formally

2022-10-18 11:46 UTC, warren830 commented on pkg/util/downloader/resource_test.go
> +
Hmmm... Sorry,  I thought this should be formatted automatically

2022-10-19 08:13 UTC, daniel-hutao approved these changes

2022-10-19 08:32 UTC, daniel-hutao approved these changes

2022-10-20 02:34 UTC, IronCore864 approved these changes

2022-10-20 02:34 UTC, merged