refactor: add field for resource downloader
devstream-io/devstream pull request #1250
Opened 2022-11-22 10:38 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
- add `downloader.resourceLocation` field
- refactor resource

## Related Issues
close #1249

## New Behavior (screenshots if needed)

2022-11-22 10:53 UTC, daniel-hutao requested changes

2022-11-22 10:53 UTC, daniel-hutao commented on internal/pkg/plugin/gitlabci/generic/options_test.go
> +		a                            *ci.PipelineConfig
A better variable name is needed.

2022-11-22 10:53 UTC, daniel-hutao commented on internal/pkg/plugin/gitlabci/generic/options_test.go
> +		r                            *git.RepoInfo
How about using the `repoInfo` here?

2022-11-23 05:38 UTC, aFlyBird0 approved these changes

2022-11-24 04:11 UTC, daniel-hutao approved these changes

2022-11-24 04:11 UTC, merged