feat: support for rollback in case of error in intermediate steps
devstream-io/devstream pull request #1379
Opened 2022-12-24 14:30 UTC by 0zyt

Signed-off-by: 0zyt <zyt0@duck.com>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description
When an error occurs while updating, roll back

## Related Issues
https://github.com/devstream-io/devstream/issues/1173

## New Behavior (screenshots if needed)

2022-12-26 07:48 UTC, daniel-hutao commented
@KeHaohaoke Please help to fix the ci error here. It seems like a configuration issue with build machine.

2022-12-27 04:22 UTC, daniel-hutao requested changes

2022-12-27 04:22 UTC, daniel-hutao commented on internal/pkg/upgrade/upgrade.go
> +			case 3:
If we failed in step 4, it seems like step 321 all should be rollback.

1 failed -> rollback 1
2 failed -> rollback 2,1
3 failed -> rollback 3,2,1
4 failed -> rollback 4,3,2,1

2022-12-28 05:04 UTC, aFlyBird0 reviewed
It looks like your code has been off the main branch for two months.

Please run `git fetch upstream && git rebase upstream/main` on the current branch first to update the code.
(If you are not particularly proficient with git, it is recommended that you back up your current code changes first)

@0zyt

2023-01-17 03:12 UTC, daniel-hutao approved these changes
lgtm

2023-01-17 08:56 UTC, aFlyBird0 approved these changes
Good job!

2023-01-17 08:56 UTC, merged