refactor: jira plugin
devstream-io/devstream pull request #1398
Opened 2022-12-28 10:03 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
- rename `jira-github-integ` to `jira` plugin, because we can support different scm type

## Related Issues
#1336 

## New Behavior (screenshots if needed)

2022-12-29 06:10 UTC, daniel-hutao requested changes

2022-12-29 06:10 UTC, daniel-hutao commented on docs/plugins/plugins-list.zh.md
> -| Issue Tracking         | jira-github-integ   | Jira/GitHub 整合                | [doc](jira-github-integ.md)             |
“Jira/GitHub 整合” should be updated accordingly.

2022-12-29 06:10 UTC, daniel-hutao commented on internal/pkg/plugin/jira/tpl/issuebuilder.tpl.yml
> -package jiragithub
Why still use `jira-github-integ` here?

2022-12-29 06:10 UTC, daniel-hutao commented on internal/pkg/show/config/plugins/jira.yaml
> +- name: jira-github-integ
need to be updated.

2022-12-29 13:19 UTC, daniel-hutao commented
@steinliber Please resolve the conflicts in this pr.

2022-12-30 01:58 UTC, daniel-hutao approved these changes

2022-12-30 07:08 UTC, IronCore864 approved these changes

2022-12-30 07:54 UTC, merged