feat: add use-cases for gitops-python-flask-tools
devstream-io/devstream pull request #1420
Opened 2023-01-05 10:02 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
- add use cases docs for `gitops-python-flask-tools`

*Note: these docs are based on pr #1419 is merged*

## Related Issues

## New Behavior (screenshots if needed)

2023-01-05 11:08 UTC, daniel-hutao requested changes

2023-01-05 11:08 UTC, daniel-hutao commented on docs/use-cases/gitops-python-flask/5-gitlab-dtm-tools.md
> +首先需要初始化来下载插件：
This line needs to be translated to English.

2023-01-05 11:08 UTC, daniel-hutao commented on docs/use-cases/gitops-python-flask/5-gitlab-dtm-tools.md
> +➜ kubectl get application -n argocd
Maybe it's better to use $ as a terminal prompt here. Same as below.

2023-01-05 11:08 UTC, daniel-hutao commented on docs/use-cases/gitops-python-flask/5-gitlab-dtm-tools.zh.md
> +上述配置运行的前提是你的 `Gitlab` 已经配置好了共享 runner 来执行 `ci` 操作，如果你想要自动创建一个 runner， 你可以参考 [gitlab插件文档](../../plugins/github-actions.zh.md) 来配置由 `Devstream` 来创建一个项目 runner。
GitLab instead of Gitlab; DevStream instead of Devstream.

2023-01-05 11:08 UTC, daniel-hutao commented on docs/use-cases/gitops-python-flask/5-gitlab-dtm-tools.zh.md
> +现在我们就可以看到 `Gitlab` 中已经创建了对应的仓库并且 `CI` 把生成的项目镜像推送到了 `Dockerhub` 仓库。
GitLab

2023-01-06 07:43 UTC, daniel-hutao commented
@steinliber Please merge the 2 commits for they have a same message. And its type is docs, not feat.

2023-01-06 07:48 UTC, daniel-hutao approved these changes

2023-01-06 07:59 UTC, IronCore864 approved these changes

2023-01-06 08:00 UTC, merged