feat: new plugin - gitlabci-generic
devstream-io/devstream pull request #396
Opened 2022-04-07 12:37 UTC by IronCore864

# Summary

## Key Points

- [x] Documentation (new or existing) is updated.

## Description

- new plugin: gitlabci-generic
- it takes two extra inputs: template URL and template variables
- it downloads the template, then renders it using the given variables
- docs are also updated
- `dtm develop` document related refactor according to recent doc refactor
- added to `dtm show` as well

2022-04-07 12:48 UTC, daniel-hutao requested changes

2022-04-07 13:17 UTC, daniel-hutao commented
/approve

2022-04-07 13:44 UTC, imxw commented on docs/plugins/gitlabci-generic.md
> +See the [official document](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) for more information.
It would be nice to have a more specific description of what permissions the user needs at least

2022-04-08 00:59 UTC, merged

2022-05-18 02:09 UTC, IronCore864 commented
Closes #377