Feat kehao implement vault plugin
devstream-io/devstream pull request #435
Opened 2022-04-23 18:28 UTC by KeHaohaoke

Signed-off-by:  KeHao [hao.ke@merico.dev](mailto:hao.ke@merico.dev)

# Summary

Add harshicorp-vault plugin

## Key Points

- [ ] This is a breaking change.

- [x]  Documentation (new or existing) is updated.

## Description

 Downloading the all-in-one YAML file from hashicorp vault repo and applying with helm . Install vault on a existing k8s by replicas: 3
### Related Issues

close: #425 

### Screenshots

- **init** 

![image](https://user-images.githubusercontent.com/103085894/164934331-5b310167-3014-4db9-9e06-80650f13b2ba.png)

- **apply**
![image](https://user-images.githubusercontent.com/103085894/164934448-14eb5bb3-1bdf-41bb-b8fb-33d566d5afb9.png)

- **config.yaml**
![image](https://user-images.githubusercontent.com/103085894/164934464-7e16fa3f-108e-4b6a-a841-a8ca2c6cb3b1.png)

- **devstream.state**
![image](https://user-images.githubusercontent.com/103085894/164934684-7bd7a52d-0b5d-4688-a656-2a074d88a496.png)

**check status by kubectl**
![image](https://user-images.githubusercontent.com/103085894/164934733-817a8b05-2b8b-49f7-a537-3988b5dc1c33.png)

- **delete**
![image](https://user-images.githubusercontent.com/103085894/164934992-30038a60-811b-4c96-b57d-a3da9dabd27c.png)

2022-04-23 19:52 UTC, KeHaohaoke commented
doc for vault plugin : https://github.com/devstream-io/website/pull/13

2022-04-24 01:19 UTC, daniel-hutao commented
#425 is a pr, not issue. And why do you created 2 pr for this feature?

2022-04-24 01:30 UTC, KeHaohaoke commented
> #425 is a pr, not issue. And why did you create 2 pr for this feature?

#425 pr rom myself repo. This  pr  from merico-dev according to develop regulation.

2022-04-24 01:58 UTC, KeHaohaoke commented
https://github.com/devstream-io/devstream/pull/435/commits/b0cf67fea0db165bd1d43480a70d26981a08ad57

modify name and namespace

2022-04-24 05:14 UTC, IronCore864 commented
> doc for vault plugin : [devstream-io/website#13](https://github.com/devstream-io/website/pull/13)

Doc is reviewed. The quality is not good. Please rework.

2022-04-24 05:15 UTC, IronCore864 commented
> #425 is a pr, not issue. And why did you create 2 pr for this feature?

@KeHaohaoke "Closes" should be used on "issues", not "PRs."

2022-04-24 05:15 UTC, IronCore864 commented
Duplicated commit messages, and one commit message failed lint-commit-message.

2022-04-25 01:49 UTC, daniel-hutao requested changes

2022-04-25 03:00 UTC, KeHaohaoke commented on cmd/plugin/hashicorp-vault/main.go
> +// Create implements the create of vault.
> Comment error with plugin name

Corrected comments in source file

2022-04-25 03:00 UTC, KeHaohaoke commented on internal/pkg/plugin/hashicorpvault/create.go
> +// Create creates hashicorpvault with provided options.
> hashicorp-vault

Corrected comments in source file

2022-04-27 06:49 UTC, daniel-hutao approved these changes

2022-04-28 07:46 UTC, merged