docs: mkdocs.zh.md
devstream-io/devstream pull request #743
Opened 2022-06-23 11:53 UTC by amdaous

Signed-off-by: “amdaous <dreamlife1991@163.com>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [ ] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [ ] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description

Translate “Setting up Navigation” section in the docs/development/mkdocs.md

## Related Issues

#742 

## New Behavior (screenshots if needed)

2022-06-24 02:39 UTC, aFlyBird0 commented
Thank you for your initiative in submitting the issue and completing the translation! ❤️ 

To move things forward quickly, I have made a few changes to make the translation more accurate. I hope you don't mind!

2022-06-24 02:40 UTC, aFlyBird0 approved these changes

2022-06-24 08:13 UTC, imxw requested changes

2022-06-24 08:13 UTC, imxw commented on docs/development/mkdocs.zh.md
>  - 更新`/mkdocs.yml`文件，更新`nav:`部分。这是整个文档网站的目录。
Please synchronize with the English version here 
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/16207029/175493372-379847ec-2f35-4467-bc19-778da9d4a8b6.png">

2022-06-24 08:53 UTC, IronCore864 commented
@imxw please help to make sure that the contributor's PR is merged.

2022-06-24 09:03 UTC, imxw approved these changes

2022-06-27 01:34 UTC, IronCore864 approved these changes

2022-06-27 01:34 UTC, merged