docs: update jenkins plugin doc
devstream-io/devstream pull request #784
Opened 2022-06-29 06:35 UTC by IronCore864

Signed-off-by: Tiexin Guo <guotiexin@gmail.com>

## Description

Update Jenkins plugin's documentation according to the latest change, both English and Chinese.

2022-06-29 06:45 UTC, aFlyBird0 approved these changes

2022-06-30 03:51 UTC, daniel-hutao requested changes

2022-06-30 03:51 UTC, daniel-hutao commented on docs/plugins/jenkins.zh.md
> +如果 k8s 和 dtm 运行在不同的主机上，比如 k8s 运行在 虚拟机或者Docker容器中：
Should we add space around the "Docker"?

2022-06-30 03:51 UTC, daniel-hutao commented on docs/plugins/jenkins.md
> +2. Create the data directory manually in the host where Kubernetes is running. Here's how:
Kubernetes? kubernetes? k8s?

2022-06-30 05:31 UTC, aFlyBird0 approved these changes
LGTM.

2022-06-30 06:30 UTC, daniel-hutao approved these changes

2022-06-30 06:30 UTC, merged