fix: show non-existent plugin config
devstream-io/devstream pull request #847
Opened 2022-07-13 07:08 UTC by iyear

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
I remove the default value of `template`. We can discuss better solution.
## Related Issues
close #841 

## New Behavior (screenshots if needed)
![image](https://user-images.githubusercontent.com/61452000/178672301-08de3b9c-a56c-4433-a5b8-73bf92986df5.png)

2022-07-13 14:01 UTC, daniel-hutao commented
> In #795 , @IronCore864 thinks that templates are less suitable to be exported by command, but are suitable to be placed under `/examples`. The user gets the yaml file as a download.
> 
> Now two concurrent `quickstart.yaml` and `gitops.yaml` are preventing maintainability. If a solution can be discussed, I can fix it in the meantime.
> 
> @daniel-hutao @aFlyBird0

@iyear I've left a comment under #795. Let's have more discussions there.

2022-07-15 07:46 UTC, daniel-hutao commented
For quickstart printing logic, my original design was "when `-p` does not exist, `-t` defaults to equal `quickstart` when `-t` is not set; when `-p` exists, `-t` does not take effect". 

We can follow this idea to fix it first. As for whether to delete the logic of `quickstart` configuration printing, we can wait until the end of the #795 discussion and implement it in a separate pr. @iyear

2022-07-15 07:47 UTC, daniel-hutao requested changes
see https://github.com/devstream-io/devstream/pull/847#issuecomment-1185273569

2022-07-15 08:11 UTC, iyear commented
@daniel-hutao https://github.com/devstream-io/devstream/blob/2c8ba2d9e1cae2b0b1a1569a7d723dfb4b894173/internal/pkg/show/config/config.go#L22-L24

Then I have to remove this code.
Only one of the `-p` and `-t` args can be allowed to carry a default value.

2022-07-18 03:19 UTC, daniel-hutao commented
I looked at the code and we need to prioritize support for `default config` printing, i.e. `dtm show config` can only print [internal/pkg/show/config/default.yaml](https://github.com/devstream-io/devstream/blob/d6875bbf7186cda670334f72f521ca314db29e38/internal/pkg/show/config/default.yaml). so we had to drop the default printing logic for `quickstart`. So, let's just keep the `-t quickstart` support.

@iyear Please also check if the documentation needs to be updated.

Releated issue: #597

2022-07-18 03:21 UTC, daniel-hutao requested changes

2022-07-18 03:21 UTC, daniel-hutao commented on internal/pkg/show/config/config.go
> +	if tmpl, ok := templates[viper.GetString("template")]; ok {
What if a user type: `dtm show config -t abcd`?

It is possible that some exception input checks are needed here to inform the user what parameters are supported when the user enters an incorrect parameter.

2022-07-19 03:48 UTC, iyear commented
@daniel-hutao Is it possible to review and then merge in? I will start working on #795, otherwise it will cause a conflict.

2022-07-21 02:09 UTC, merged