feat: add backend|pluginmanager|statemanager ut
devstream-io/devstream pull request #848
Opened 2022-07-13 14:35 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description

- Add internal/pkg/backend package `ut`
- Add internal/pkg/pluginmanager package `ut`
- Add internal/pkg/statemanager package `ut`

## Related Issues
#845

2022-07-15 07:37 UTC, daniel-hutao requested changes

2022-07-15 07:37 UTC, daniel-hutao commented on internal/pkg/backend/backend_test.go
> +	"github.com/devstream-io/devstream/internal/pkg/backend"
. "github.com/onsi/ginkgo/v2"
 	. "github.com/onsi/gomega"

	"github.com/devstream-io/devstream/internal/pkg/backend"
 	"github.com/devstream-io/devstream/internal/pkg/configloader"

2022-07-15 07:37 UTC, daniel-hutao commented on internal/pkg/backend/backend_test.go
> +
Extra blank lines

2022-07-15 07:37 UTC, daniel-hutao commented on internal/pkg/backend/backend_test.go
> +
Extra blank lines

2022-07-15 07:37 UTC, daniel-hutao commented on internal/pkg/backend/backend_test.go
> +
Extra blank lines

2022-07-15 07:37 UTC, daniel-hutao commented on internal/pkg/backend/local/local_test.go
> +	"io/ioutil"
Please note the formatting of the import format and check all files.

2022-07-15 07:37 UTC, daniel-hutao commented on internal/pkg/backend/local/local_test.go
> +
Extra blank lines. Please check all files below.

2022-07-18 00:45 UTC, IronCore864 approved these changes

2022-07-18 00:46 UTC, IronCore864 commented
Great work. Need another reviewer here for the new tests.

2022-07-18 04:23 UTC, iyear approved these changes

2022-07-18 08:09 UTC, hxcGit approved these changes

2022-07-18 08:18 UTC, daniel-hutao approved these changes

2022-07-18 08:18 UTC, merged