Docs: add new translated blog - Tool, State, and Resource - Chinese Version
devstream-io/devstream pull request #852
Opened 2022-07-14 11:09 UTC by LauraJW

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [X] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [ ] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description

## Related Issues
#724
## New Behavior (screenshots if needed)

2022-07-15 01:06 UTC, steinliber commented
A kind reminder that you haven't signed off on your commit(s) yet. Check out our [official doc](https://docs.devstream.io/en/latest/contributing_guide/#sign-your-commits) to learn how to do this.

2022-07-15 07:34 UTC, daniel-hutao requested changes
I found that this document does not correspond exactly to the English version. Please check the latest English version of the document and update it, thanks!

https://docs.devstream.io/en/latest/core-concepts/core-concepts/

2022-07-16 10:14 UTC, aFlyBird0 commented
Hi @LauraJW , thanks for your contribution! Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!

Here are a few useful things for you to continue your open-source journey:

- If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
- Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
- Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

We made changes to your PR directly so that your contribution can be merged quicker. We hope you don't mind!

A kind reminder that you haven't signed off on your commit(s) yet. Check out our [official doc](https://docs.devstream.io/en/latest/contributing_guide/#sign-your-commits) to learn how to do this. Also, DevStream community follows the [conventional commits specification](https://www.conventionalcommits.org/eXn/v1.0.0/). Please read our [doc](https://docs.devstream.io/en/latest/development/commit-messages/) and update your commit message.

2022-07-16 10:15 UTC, aFlyBird0 approved these changes

2022-07-18 00:47 UTC, IronCore864 approved these changes

2022-07-18 03:46 UTC, daniel-hutao approved these changes

2022-07-18 05:41 UTC, merged