feat: pkg/uil/downloader Enhancement
devstream-io/devstream pull request #857
Opened 2022-07-16 06:22 UTC by jxs1211

Signed-off-by: xian-jie.shen <327411586@qq.com>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
trying to resolve:
- OOM risk
- adding url's empty check to make the fail fast
- add more test case to increase the test coverage

## Related Issues
see https://github.com/devstream-io/devstream/issues/833 for the details

## New Behavior (screenshots if needed)
- the OOM risk is here
![image](https://user-images.githubusercontent.com/6358406/179342795-6e731e5c-b525-4906-83cb-d4a8727ab04f.png)

- ut coverage hit 100%
```sh
[going@dev downloader]$ go tool cover -func=coverage.out
github.com/devstream-io/devstream/pkg/util/downloader/downloader.go:12: Download        100.0%
total:                                                                  (statements)    100.0%
```

2022-07-18 00:22 UTC, IronCore864 requested changes

2022-07-18 00:22 UTC, IronCore864 commented on pkg/util/downloader/downloader_test.go
> +	// Context("when the Yaml parses fails", func() {
"Deadcode" can be removed.

2022-07-18 00:23 UTC, IronCore864 commented
Great work. There are a few lines of commented-out code (dead code) that can be removed, FYI.

2022-07-20 03:27 UTC, hxcGit approved these changes

2022-07-20 03:39 UTC, IronCore864 approved these changes

2022-07-20 03:39 UTC, merged