fix: plugin installed by helm status inconsistent
devstream-io/devstream pull request #904
Opened 2022-07-25 06:52 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [ ] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description

Fix inconsistent status error for plugin installed by the helm.

## Related Issues

close #896

2022-07-26 02:24 UTC, aFlyBird0 requested changes

2022-07-26 02:24 UTC, aFlyBird0 commented on internal/pkg/plugininstaller/helm/state.go
> +		state.Workflows.AddStatefulset(ds.Name, ds.Ready)
a small mistake.

`AddAddDaemonset`

2022-07-26 10:20 UTC, aFlyBird0 approved these changes

2022-07-28 01:35 UTC, iyear approved these changes

2022-07-28 01:36 UTC, daniel-hutao approved these changes
lgtm

2022-07-28 01:36 UTC, merged