feat: add plugin default config
devstream-io/devstream pull request #962
Opened 2022-08-08 02:36 UTC by steinliber

Signed-off-by: Meng JiaFeng <jiafeng.meng@merico.dev>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description
- All helm plugins support the default value 

## Related Issues
#523 #526 #527 #513

## New Behavior (screenshots if needed)
Jenkins config Before
![image](https://user-images.githubusercontent.com/13215800/183327007-0f46acfc-1727-4178-9eff-38549912eb7a.png)

After
![image](https://user-images.githubusercontent.com/13215800/183326927-eb441da7-56af-40a1-aea0-e3bb5172eb04.png)

2022-08-09 01:17 UTC, iyear commented on docs/plugins/artifactory.md
> +Currently, except for `values_yaml` and default configs, all the parameters in the example above are mandatory.
I see this sentence, but there is no action in the code to set a default value to `values_yaml`.

It is also possible that I missed it.

2022-08-09 01:33 UTC, iyear commented on docs/plugins/jenkins.md
> +| chart.timeout | 10m | this config will wait 10 minutes to deploy |
The default value in the yaml file is 5 minutes, but the code is set to 10 minutes.

2022-08-09 01:33 UTC, iyear commented on docs/plugins/jenkins.zh.md
> +| chart.timeout | 10m | 等待部署成功的时间 |
The default value in the yaml file is 5 minutes, but the code is set to 10 minutes.

2022-08-09 01:36 UTC, iyear commented on docs/plugins/kube-prometheus.md
> +| chart.timeout | 10m | this config will wait 10 minutes to deploy |
The default value in the yaml file is 5 minutes, but it is set to 10 minutes in the code and default config.

2022-08-09 01:41 UTC, iyear commented
I have compared the original yaml, the code `defaultHelmConfig` and the default config table in the doc.

2022-08-09 02:08 UTC, iyear approved these changes
More user-friendly!

2022-08-09 02:27 UTC, aFlyBird0 commented on docs/plugins/argocd.md
> +|    repo.name     | argo                                 | helm repo name                                   |
I see that in the first column of your table, some of the documents are center-aligned like this, and some of them are left-aligned.

2022-08-09 02:30 UTC, aFlyBird0 commented on docs/plugins/argocd.md
> +|    repo.name     | argo                                 | helm repo name                                   |
After testing, I found that if you edit the file a bit (e.g. delete a space in the table and add it back), then Ctrl+S, Goland will automatically align it to the left for you. Try it?

2022-08-09 02:35 UTC, aFlyBird0 commented on docs/plugins/harbor.md
> +| chart.timeout    | 10m                      | this config will wait 10 minutes to deploy |
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36830265/183551049-c1b5e6e7-018a-4d94-9891-a797b2285198.png">

Please edit this comment.

2022-08-09 02:36 UTC, aFlyBird0 commented on docs/plugins/argocd.md
> +|    repo.name     | argo                                 | helm repo name                                   |
> it's editor's operation， which one looks better

I prefer the left-aligned one?

2022-08-09 02:46 UTC, aFlyBird0 requested changes

2022-08-09 02:46 UTC, aFlyBird0 commented on docs/plugins/artifactory.zh.md
> +| chart.timeout    | 10m                     | 等待部署成功的时间                |
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36830265/183551479-1f18baa4-f966-4c19-9205-85f02dc6a329.png">

2022-08-09 02:46 UTC, aFlyBird0 commented on docs/plugins/openldap.md
> +|  chart.timeout   | 5m                                        | this config will wait 10 minutes to deploy |
"5m"   vs "this config will wait 10 minutes to deploy"

2022-08-09 02:46 UTC, aFlyBird0 commented on docs/plugins/hashicorp-vault.md
> +| chart.timeout    | 5m                                  | this config will wait 10 minutes to deploy |
"5m" vs "this config will wait 10 minutes to deploy"

2022-08-09 02:46 UTC, aFlyBird0 commented on docs/plugins/hashicorp-vault.md
> +| chart.wait       | true                                | whether to wait until install is complete  |
"install" is a verb.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/36830265/183552069-863e24b1-7f47-4fe9-811d-0cd466cc411f.png">

You could use "whether to wait until the installation is complete"

2022-08-09 02:48 UTC, aFlyBird0 commented
A very helpful documentation improvement for users!👏

2022-08-10 01:30 UTC, aFlyBird0 approved these changes

2022-08-10 07:46 UTC, daniel-hutao commented
@steinliber Please resolve the conflicts. Then we can merge this pr asap.

2022-08-10 08:57 UTC, IronCore864 approved these changes

2022-08-10 15:50 UTC, closed without merging